# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phodo.models


class Migration(migrations.Migration):

    dependencies = [
        ('phodo', '0003_auto_20160926_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='picture',
            field=models.ImageField(upload_to=phodo.models.pic_name),
        ),
        migrations.AlterField(
            model_name='pic',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phodo.Tag'),
        ),
    ]
