# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phodo', '0004_auto_20160928_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='picture',
            field=models.URLField(max_length=80),
        ),
    ]
