# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phodo', '0005_auto_20160929_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=40)),
                ('domain', models.CharField(default='wechat', max_length=20)),
                ('last_login', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
