# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 4, 34, 55, 604164, tzinfo=utc), verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='charger',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='parking',
            name='confirmby',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='parking',
            name='user',
            field=models.CharField(default='test', max_length=40),
        ),
        migrations.AlterField(
            model_name='parking',
            name='userend',
            field=models.BooleanField(default=False),
        ),
    ]
