# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160906_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start'),
        ),
    ]
