# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(default='wechat', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
